name: Windows

on:
  workflow_call:

jobs:
  benchmark:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/benchmark.bat --transfer-count 4000

  c_sample:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: .\scripts\install_zig.bat
      - run: .\scripts\build.bat c_sample

  cli_client_integration:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/build.bat cli_client_integration
      - run: ./zig-out/bin/cli_client_integration.exe
